### ISSUE TITLE
why do not use the reserverd bit？

### ISSUE THREAD

**Issue by pengbinbin1** [ovn-org/ovn#73]
In the commit b07f1bc3d068e231e40840b0d977bd57158987fd,the commit log like below :**Because of limited space in VXLAN VNI to pass over all three of -datapath id, ingress port, egress port - the implementation ignores ingress; and splits the remaining 24 bits of VNI into two chunks, 12 bits each - one for datapath and one for egress port**
but why do not use the reserved bit in vxlan header ?thank you .

**Comment by numansiddique** [comment]
@booxter Any comments ?

**Comment by pengbinbin1** [comment]
I have another question,what is the affect if we ignore the ingress port? can we also ignore the egress port ? and what does the ingress port and egress port do ? i am a little not understand about that ,looking forward to you reply,thank you.

**Comment by blp** [comment]
We don't use the reserved bit because it's reserved. If you try to use it you will break VXLAN.

Omitting the ingress port means that ACLs that match on the ingress port won't work.

If we omitted the egress port then the hypervisor that receives the packet wouldn't know where it should go.

I don't see a description of a bug here, so I'm closing the report. If you want to discuss the OVN design, please use the mailing lists.
